DEVICE          : cuda                        # device used for training and evaluation (cpu, cuda, cuda0, cuda1, ...)
SAVE_DIR        : 'output/MMSFormer'          # output folder name used for saving the model, logs and inference results
GPUs            : 2
GPU_IDs         : [0, 1]
USE_WANDB       : true
WANDB_NAME      : 'MMSF-MCubeS-RGBNAD'        # name for the run

MODEL:
  NAME          : MMSFormer                                         # name of the model you are using
  BACKBONE      : MMSFormer-B2                                      # model variant
  PRETRAINED    : 'checkpoints/pretrained/segformer/mit_b2.pth'     # backbone model's weight 
  RESUME        : ''                                                # checkpoint file

DATASET:
  NAME          : MCubeS                                          # dataset name to be trained with (camvid, cityscapes, ade20k)
  ROOT          : 'data/MCubeS'                                 # dataset root path
  IGNORE_LABEL  : 255
  # MODALS        : ['image']
  # MODALS        : ['image', 'nir'] 
  # MODALS        : ['image', 'aolp']
  # MODALS        : ['image', 'dolp']
  # MODALS        : ['image', 'aolp', 'nir']
  # MODALS        : ['image', 'aolp', 'dolp']
  MODALS        : ['image', 'nir', 'aolp', 'dolp']

TRAIN:
  IMAGE_SIZE    : [512, 512]      # training image size in (h, w) === Fixed in dataloader, following MCubeSNet
  BATCH_SIZE    : 4               # batch size used to train
  EPOCHS        : 500             # number of epochs to train
  EVAL_START    : 0               # evaluation interval during training
  EVAL_INTERVAL : 1               # evaluation interval during training
  AMP           : true            # use AMP in training
  DDP           : false           # use DDP training

LOSS:
  NAME          : OhemCrossEntropy # loss function name
  CLS_WEIGHTS   : false            # use class weights in loss calculation

OPTIMIZER:
  NAME          : adamw           # optimizer name
  LR            : 0.00006         # initial learning rate used in optimizer
  WEIGHT_DECAY  : 0.01            # decay rate used in optimizer 

SCHEDULER:
  NAME          : warmuppolylr    # scheduler name
  POWER         : 0.9             # scheduler power
  WARMUP        : 10              # warmup epochs used in scheduler
  WARMUP_RATIO  : 0.1             # warmup ratio
  

EVAL:
  MODEL_PATH    : 'output/MMSFormer/MMSFormer_MiT_B2_MCubeS_RGBNAD.pth'
  IMAGE_SIZE    : [1024, 1024]    # evaluation image size in (h, w)                       
  BATCH_SIZE    : 2               # batch size used to train
  MSF: 
    ENABLE      : false                                   # multi-scale and flip evaluation  
    FLIP        : true                                    # use flip in evaluation  
    SCALES      : [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]       # scales used in MSF evaluation                
